repos:
  - repo: local
    hooks:
      - id: generate-tests
        name: Generate Unit Tests
        entry: python ./LLM/02_Generate_unit_test/generate_tests.py
        language: system
        types: [python]
        pass_filenames: false