repos:
  - repo: local
    hooks:
      - id: generate-tests
        name: Generate Unit Tests
        entry: python generate_tests.py
        language: system
        types: [python]
        pass_filenames: false