[project]
name = "02-generate-unit-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.68.2",
    "pytest>=8.3.5",
    "ragas>=0.2.14",
    "rouge-score>=0.1.2",
]
